apiVersion: batch/v1
kind: Job
metadata:
  name: andrewbailey-gaussian-median-2-$TS
spec:
  ttlSecondsAfterFinished: 6000
  template:
    spec:
#      template:
#        metadata: # Apply a lable saying that we use NUMA node 0
#          labels:
#            usesnuma0: "Yes"
#      affinity: # Say that we should not schedule on the same node as any other pod with that label
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: usesnuma0
#                    operator: In
#                    values:
#                      - "Yes"
#              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: main
          imagePullPolicy: Always
          image: ucscbailey/signalalign@sha256:7a60d7e5b8298c77acb43a9cb499ae81ce197fa476f4e4a26ed5f492379bb27b
          env:
            - name: N_THREADS
              value: "30"
            - name: USE_MEDIAN
              value: "true"
            - name: MIN_SD
              value: "2"
          command:
            - /bin/bash
            - -c
            - |
              set -e
              DEBIAN_FRONTEND=noninteractive apt-get -qq update
              DEBIAN_FRONTEND=noninteractive apt-get -qq install -y awscli git
              #             download data
              aws s3 cp --no-progress s3://bailey-k8s/rrna_yeast_data/gaussian_distribution_testing.sh .
              bash gaussian_distribution_testing.sh "$(N_THREADS)" "$(USE_MEDIAN)" "$(MIN_SD)"
              echo DONE
          volumeMounts:
            - mountPath: /root/.aws
              name: s3-credentials
            - mountPath: /data
              name: scratch-volume
          resources:
            limits:
              cpu: 30
              memory: "150Gi"
              ephemeral-storage: "350Gi"
      restartPolicy: Never
      volumes:
        - name: scratch-volume
          emptyDir: { }
        - name: s3-credentials
          secret:
            secretName: shared-s3-credentials
  backoffLimit: 0
