apiVersion: batch/v1
kind: Job
metadata:
  name: andrewbailey-inference-alt-c-$TS
spec:
  ttlSecondsAfterFinished: 6000
  template:
    spec:
      containers:
        - name: main
          imagePullPolicy: Always
          image: ucscbailey/signalalign@sha256:d868685fa01ef72b83c9b914c760cbfda309a8966569cffab503a5a34b28c82a
          env:
            - name: N_THREADS
              value: "30"
          command:
            - /bin/bash
            - -c
            - |
              set -e
              DEBIAN_FRONTEND=noninteractive apt-get -qq update
              DEBIAN_FRONTEND=noninteractive apt-get -qq install -y awscli git python3-distutils
              #             download data
              aws s3 cp --no-progress s3://bailey-k8s/rrna_yeast_data/scripts/inference.sh .
              bash inference.sh "$(N_THREADS)"
              echo DONE
          volumeMounts:
            - mountPath: /root/.aws
              name: s3-credentials
            - mountPath: /data
              name: scratch-volume
          resources:
            limits:
              #              cpu: 2
              #              memory: "10Gi"
              #              ephemeral-storage: "350Gi"
              cpu: 30
              memory: "200Gi"
              ephemeral-storage: "350Gi"
      restartPolicy: Never
      volumes:
        - name: scratch-volume
          emptyDir: { }
        - name: s3-credentials
          secret:
            secretName: shared-s3-credentials
  backoffLimit: 0
