apiVersion: batch/v1
kind: Job
metadata:
  name: andrewbailey-mrna-supervised-$TS
spec:
  ttlSecondsAfterFinished: 6000
  template:
    spec:
#      template:
#        metadata: # Apply a lable saying that we use NUMA node 0
#          labels:
#            usesnuma0: "Yes"
#      affinity: # Say that we should not schedule on the same node as any other pod with that label
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: usesnuma0
#                    operator: In
#                    values:
#                      - "Yes"
#              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: main
          imagePullPolicy: Always
          image: ucscbailey/signalalign@sha256:d868685fa01ef72b83c9b914c760cbfda309a8966569cffab503a5a34b28c82a
          env:
            - name: N_THREADS
              value: "30"
            - name: UNSUP_FREQ_THRESHOLD
              value: "0"
            - name: ALL_KMERS
              value: "false"
            - name: UNSUP
              value: "false"
            - name: USE_IVT_TRAINING
              value: "false"

          command:
            - /bin/bash
            - -c
            - |
              set -e
              DEBIAN_FRONTEND=noninteractive apt-get -qq update
              DEBIAN_FRONTEND=noninteractive apt-get -qq install -y awscli git python3-distutils
              #             download data
              aws s3 cp --no-progress s3://bailey-k8s/rrna_yeast_data/unsupervised.sh .
              bash unsupervised.sh "$(N_THREADS)" "$(UNSUP_FREQ_THRESHOLD)" "$(ALL_KMERS)" "$(UNSUP)" "$(USE_IVT_TRAINING)"
              echo DONE
          volumeMounts:
            - mountPath: /root/.aws
              name: s3-credentials
            - mountPath: /data
              name: scratch-volume
          resources:
            limits:
#              cpu: 2
#              memory: "10Gi"
#              ephemeral-storage: "350Gi"
              cpu: 30
              memory: "150Gi"
              ephemeral-storage: "350Gi"
      restartPolicy: Never
      volumes:
        - name: scratch-volume
          emptyDir: { }
        - name: s3-credentials
          secret:
            secretName: shared-s3-credentials
  backoffLimit: 0
